### PR TITLE
added prefix for tagName

### PR DESCRIPTION
**Pull request by RichardGottschalk**
I got several projects in one git repository so the tags need a prefix.
By the way, great plugin!

### CODE REVIEW

**Comment by RichardGottschalk** [comment]
well, I don't know why the tests are failing, I do not have any groovy IDE... I hope you can add/fix those prefixes :smile:

**Comment by netzwerg** [comment]
Thanks for the patch and the positive feedback!

I don't quite understand the motivation behind your addition. In Git, a tag by design always applies to the complete repository. So even if you have several projects in one repository, tagging them with a specific prefix will always tag the complete repo.

Could you elaborate on your setup/goal please?

**Comment by RichardGottschalk** [comment]
just fixed the issue, sorry for that.
also added a test for the prefix.

Tags are supported by many git plugins and I think they are pretty usefull if you use a separated (maven) repository like nexus or even mavencentral for your versions. 
In case you use git as repository they are indeed not required.

**Comment by netzwerg** [comment]
Merged & released, thanks again! 0.4 is up on Bintray/jCenter and should be available via Gradle Central Plugin Repository in a minute...

**Comment by RichardGottschalk** [comment]
Thank you! Works perfect!

**Pull request merged**
