### PR TITLE
fix formatting of commit message

### PR DESCRIPTION
**Pull request by stefanleh**

### CODE REVIEW

**Comment by stefanleh** [comment]
The build fails cause of wrong JAVA_HOME :(
Maybe its time to upgrade from Java 1.6?

**Comment by netzwerg** [comment]
When applying the PR locally (on OSX), I get extra quotation marks in my git log:

screen shot 2017-09-20 at 14 58 49

This is not desirable. What is the behavior on your Windows machine?

**Comment by stefanleh** [comment]
grafik

**Comment by stefanleh** [comment]
git log

commit 54a11fcee5ee866c7ee3ee2c0ead57f2356515c2
Author: Stefan Lehmann <stefan.lehmann@unic.com>
Date:   Wed Sep 20 15:49:29 2017 +0200

    Release v0.0.3

commit c2bb4107923a572dcf34373544d0a1bce3cff923
Author: Stefan Lehmann <stefan.lehmann@unic.com>
Date:   Wed Sep 20 15:46:59 2017 +0200

    Prepare next release v0.0.3-SNAPSHOT

commit 87d0338b9b3a646dc6a07ad24da883cc68cd703e
Author: Stefan Lehmann <stefan.lehmann@unic.com>
Date:   Wed Sep 20 15:46:59 2017 +0200

    Release v0.0.2

commit 89ef44c0d373941d8bb446071efd2c815f9f8d49
Author: Stefan Lehmann <stefan.lehmann@unic.com>
Date:   Wed Sep 20 15:46:49 2017 +0200

    test

commit 49304fd82afaf3dd7dc57dfa036e6061ed20eb92
Author: Stefan Lehmann <stefan.lehmann@unic.com>
Date:   Wed Sep 20 15:41:48 2017 +0200

    Prepare next release v0.0.2-SNAPSHOT

**Comment by stefanleh** [comment]
Ok, i removed the quotation marks and it does not complain about it (but still the exit status is bad). Sorry about the trouble. I will close this PR and make a new one only containing the fix for the output logging.

**Pull request closed without merging**
